<?php
/**
 * Created by PhpStorm.
 * User: lapiscine
 * Date: 22/11/2018
 * Time: 10:17
 */

namespace AppBundle\Repository;
/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AuteurRepository extends \Doctrine\ORM\EntityRepository
{


    public function getAuteurPays($pays)
    {
        $queryBuilder = $this->createQueryBuilder('a');

        $query = $queryBuilder
            ->select('a')
            ->where('a.pays=:pays')
            ->setParameter('pays', $pays)
            ->getQuery();

        $results = $query->getArrayResult();

        return $results;


    }



    public function getLikeAuteur($word){

        //definition de la table dans laquelle onva chercher les infos
        $queryBuilder = $this->createQueryBuilder('a');
        //definition de la requete dans la table choisie
        $query = $queryBuilder
            ->select('a')
            ->where('a.biographie LIKE :word')
            ->setParameter('word','%'.$word.'%')
            ->getQuery();
        //je récupere un array
        $results = $query->getArrayResult();

        return $results;
    }

}