<?php

namespace AppBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBooKsGenre($genre){

        //la variable queryBuilder a une instance de queryBuilder, avec pour alias l
        $queryBuilder=$this->createQueryBuilder('l');
        //
        $query= $queryBuilder
            ->select('l')
            //where est une condition qui donne access si la variable est égale a celle qui est demandé
            ->where('l.genre=:genre')
            //le set parameter va faire la verification entre :genre et $genre
            ->setParameter('genre', $genre)
            //getQuery() elle permet de recuperer la requet generé
            ->getQuery();
//on met les résultat de la requet dans une variable
        $results = $query->getArrayResult();

        return $results;










    }









}
